Version tags
VariantEffect/mavedb pull request #153
Opened 2021-09-12 17:52 UTC by harmatt

add version_tag atribute to scoreset

2021-09-16 00:49 UTC, EstelleDa requested changes
Change type to variant format.

2021-09-16 01:07 UTC, EstelleDa reviewed
I think this one is fine.

2021-11-24 21:27 UTC, afrubin commented on dataset/models/scoreset.py
> +        self.variant_format = "MaveDB v2.x"
This should refer to MAVE-HGVS.

2021-11-24 21:34 UTC, afrubin commented
This PR is missing a few things. Specifically, the version exists in the database but it's not displayed and the version can't be set via manage command (or any other method short of editing the database/Django admin).

The following features should be added:

- Variant version displayed on the score set page near where the license logo is.
- Variant version included in the header of downloaded .csv files.
- Variant version included in the score set metadata that's exported via the new variant API, as well as the regular Django API (although this probably happens automatically).
- Add a manage.py command `setdatatsetversion` that accepts a URN and a dataset version (as a string). See other custom manage.py commands for examples/inspiration.
- Migration files will need to be created before this can be merged.

2022-06-21 01:30 UTC, closed without merging